config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: 'session'



  api_version(:module => "V1", :path => {:value => "v1"}) do
    root 'articles#index'
    match '/foursquare' => 'foursquare#search', via: :get
    match '/foursquare/:id' => 'foursquare#find', via: :get
    resources :articles
    resources :locations
    resources :users
    match '/configuration' => 'configuration#show', via: :get
  end
  
  
  api_version(:module => "V2", :path => {:value => "v2"}, :default => true) do
    root 'articles#index'
    match '/foursquare' => 'foursquare#search', via: :get
    match '/foursquare/:id' => 'foursquare#find', via: :get
    resources :articles
    resources :locations
    resources :users
    match '/configuration' => 'configuration#show', via: :get
  end
  
end

app/models/article.rb
class Article < ActiveRecord::Base
  acts_as_taggable_on :moods, :categories
  acts_as_paranoid
  max_paginates_per 200

  belongs_to :user
  has_many :article_locations
  has_many :locations, through: :article_locations
  accepts_nested_attributes_for :article_locations

  before_save :set_default_kind
  after_update :touch_user_and_location
    
  validates :title, :content, :user_id, :mood_list, :category_list, presence: true
  validates :content, length: {maximum: 270}
  
  
  scope :by_mood, -> mood { tagged_with(mood, on: :moods)}
  scope :by_category, -> category { tagged_with(category, on: :categories)}
  scope :by_user, -> user_ids { user_ids ? where(user_id: user_ids) : where(true)}
  scope :by_lat_long, -> lat, long, radius = 1000 { joins(:locations).where(locations: {id: Location.by_lat_long(lat, long, radius).map(&:id)})}
  scope :by_location, -> location_ids {joins(:locations).where(locations: {id: location_ids})}
  

  
  def author
    user
  end
  
  private
  
  def touch_user_and_location
    user.touch
    locations.each(&:touch)
  end
  
  def set_default_kind
    self.kind ||= 'tidbit'
  end
  
  def self.collection_cache_key
    connection.select_value('select md5(ARRAY_AGG(updated_at)::text) from articles')
  end

end

app/controllers/v1/articles_controller.rb
module V1
  class ArticlesController < BaseController
    load_and_authorize_resource

    before_action :authorize_json_only, except: :show

    def index
      @articles = Article.all
      @articles = @articles.where(user_id: params[:user_id] ) if params[:user_id]
      @articles = @articles.tagged_with(params[:mood], on: :moods) if params[:mood]
      @articles = @articles.tagged_with(params[:category], on: :categories) if params[:category]
    end

    def show
    end

    def new
      @article.article_locations.new
    end

    def create
      @article.user = current_user
      respond_to do |format|
        if @article.save
          format.html { redirect_to @article, notice: 'Article added' }
          format.json { render json: @article }
        else
          format.html { render :new, alert: 'failed :(' }
          format.json
        end
      end
    end

    def edit
      @article.article_locations.first_or_initialize
    end

    def update
      respond_to do |format|
        if @article.update_attributes(article_params)
          format.html { redirect_to @article, notice: 'Article updated' }
          format.json { render json: @article }
        else
          format.html { render :new, alert: 'failed :(' }
          format.json
        end
      end
    end

    def destroy
      @article.destroy
      respond_to do |format|
        format.html { redirect_to articles_path, notice: 'Article deleted' }
        format.json
      end
    end

    private

    def authorize_json_only
      if request.format != :json
        authorize! :manage, Article, :message => "Unable to view articles"
      end
    end


    def article_params
      params.require(:article).permit(:title, :content, :foursquare_ids, article_locations_attributes: [:id, :foursquare_id], mood_list:[], category_list:[])
    end

  end
end

app/controllers/v2/articles_controller.rb
module V2
  class ArticlesController < BaseController
    before_action :authorize_json_only, except: :show

    has_scope :by_mood, type: :array
    has_scope :by_category, type: :array
    has_scope :by_user, type: :array
    has_scope :by_lat_long, using: [:lat, :long, :radius], type: :hash
    has_scope :by_location, type: :array
    
    def index
      @articles = apply_scopes(@articles)
      @articles = @articles.joins(:user, :locations).eager_load(:user, :locations) 
      @articles = @articles.where(user_id: current_user.id) if current_user && !params[:all_articles]  && request.format != :json      
      
      ## Geocoder and will_paginate/kaminari have an issue. tracked here: https://github.com/alexreisner/geocoder/issues/630
      ## Disabled kaminari for now
      # @articles = @articles.page(params[:page]).per(parms[:per_page])
      ## For now do it as an array
      # params[:offset] ||= 0
      # params[:limit] ||= 200
      # @articles = @articles.drop(params[:offset].to_i).take(params[:limit].to_i)
    end

    def show
    end

    def new
      @article.article_locations.new
    end

    def create
      @article.user = current_user
      respond_to do |format|
        if @article.save
          flash[:notice] = "Article added!! Add another? (or #{ActionController::Base.helpers.link_to('<b>go back</b>'.html_safe, articles_path)})"
          format.html { redirect_to new_article_path}
          format.json { render json: @article }
        else
          format.html { render :new, alert: 'failed :(' }
          format.json
        end
      end
    end

    def edit
      @article.article_locations.first_or_initialize
    end

    def update
      respond_to do |format|
        if @article.update_attributes(article_params)
          format.html { redirect_to articles_path, notice: 'Article updated' }
          format.json { render json: @article }
        else
          format.html { render :new, alert: 'failed :(' }
          format.json
        end
      end
    end

    def destroy
      @article.destroy
      respond_to do |format|
        format.html { redirect_to articles_path, notice: 'Article deleted' }
        format.json
      end
    end

    private

    def authorize_json_only
      if request.format != :json
        authorize! :manage, Article, :message => "Unable to view articles"
      end
    end


    def article_params
      params.require(:article).permit(:title, :content, :foursquare_ids, article_locations_attributes: [:id, :foursquare_id], mood_list:[], category_list:[])
    end

  end
end

app/controllers/v2/base_controller.rb
module V2
  class BaseController < ApplicationController
    load_and_authorize_resource
    before_filter :make_strings_into_arrays
    before_filter :set_cache_key_from_params
    before_filter :update_request_count, only: :show
    
    rescue_from CanCan::AccessDenied do |exception|
      if user_signed_in?
        render 'shared/access_denied'
      else
        redirect_to new_user_session_path
      end
    end
    
    private 
    
    def make_strings_into_arrays
      [:by_mood, :by_article, :by_user, :by_category, :by_location].each do |name|
        params[name] = [params[name]] if params[name].is_a? String
      end
    end
    
    def set_cache_key_from_params
      #these are the only params used to determine the content of the json partial FOR A SINGLE OBJECT
      @cache_key = params.slice(:by_user, :controller, :include_foursquare).hash
    end
    
    def update_request_count
      resource = instance_variable_get("@#{controller_name.singularize}")
      resource.update_column(:request_count, resource.request_count.to_i + 1)
    end
    
  end
end

app/controllers/v2/configuration_controller.rb
module V2
  class ConfigurationController < BaseController
   skip_load_resource 
    def show
      @categories = Settler.categories.value
      @moods = Settler.moods.value
    end
    
    def update
    end
    
  end
end

app/controllers/v2/foursquare_controller.rb
module V2
  class FoursquareController < BaseController
    skip_load_resource 
    def search
      venues = Foursquare.search_venues(params[:query])
      SearchMiss.create(query: params[:query]) if venues.empty?
      render json: venues
    end
    
    def find
      render json: Foursquare.fetch_venue(params[:id])
    end
  end
end

app/controllers/v2/locations_controller.rb
module V2
  class LocationsController < BaseController
    has_scope :by_mood, type: :array
    has_scope :by_category, type: :array
    has_scope :by_user, type: :array
    has_scope :by_lat_long, using: [:lat, :long, :radius], type: :hash
    
    
    def index      
      @locations = apply_scopes(@locations)  
      # Use eager load to avoid including all users when locations are filtered by a specific user.
      @locations = @locations.joins(articles: :user).eager_load(:articles, articles: :user)      
            
      ## Geocoder and will_paginate/kaminari have an issue. tracked here: https://github.com/alexreisner/geocoder/issues/630
      ## Disabled kaminari for now
      # @locations = @locations.page(params[:page]).per(parms[:per_page])
      ## For now do it as an array
      # params[:offset] ||= 0
      # params[:limit] ||= 200
      # @locations = @locations.drop(params[:offset].to_i).take(params[:limit].to_i)
    end
    
  end
end

app/controllers/v2/users_controller.rb
module V2
  class UsersController < BaseController
    before_action :authorize_json_only
    
    has_scope :by_mood, type: :array
    has_scope :by_category, type: :array
    has_scope :by_lat_long, using: [:lat, :long, :radius], type: :hash
    has_scope :by_article, type: :array
    has_scope :by_location, type: :array
  
    def index
      @users = apply_scopes(@users)
      @users = @users.joins(articles: :locations).eager_load(:articles, articles: :locations) 


      ## Geocoder and will_paginate/kaminari have an issue. tracked here: https://github.com/alexreisner/geocoder/issues/630
      ## Disabled kaminari for now
      # @users = @users.page(params[:page]).per(parms[:per_page])
      ## For now do it as an array
      # params[:offset] ||= 0
      # params[:limit] ||= 200
      # @users = @users.drop(params[:offset].to_i).take(params[:limit].to_i)    
    end
  
    def show
    end
  
    def new
    end
  
    def create
      @user.role = 'member'
      if @user.save
        if user_params[:avatar].present? 
          flash[:notice] = 'Go crop yo-self!'
          render :crop
        else
          flash[:notice] = 'Saved. Thank you!'
          redirect_to users_path
        end
      else
        render :new
      end
    end
  
    def edit
    end
  
    def update
      # required for settings form to submit when password is left blank
      if params[:user][:password].blank?
         params[:user].delete("password")
         params[:user].delete("password_confirmation")
      end
    
      if @user.update_attributes(user_params)
        if user_params[:avatar].present?
          flash[:notice] = 'Go crop yo-self!'
          render :crop
        else
          flash[:notice] = "Relax, you've been saved..."
          redirect_to articles_path
        end
      else
        render :edit
      end
    end
  
    def destroy
      @user.destroy
      respond_to do |format|
        format.html {redirect_to users_path }
        format.json
      end
    end
  
  
    private

    def authorize_json_only
      if request.format != :json
        authorize! :manage, User, :message => "Unable to view users"
      end
    end
  
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :about,
                                    :website_url, :twitter_handle, :expert_in, :nationality, :profession,
                                    :avatar, :avatar_cache, :crop_x, :crop_y, :crop_w, :crop_h)
    end
  
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/v2/articles/_article.html.erb
<tr>
  <%= content_tag :td, article.locations.map(&:name).join(', ') %>

  <%= content_tag :td, article.title %>
  <%= content_tag :td, article.content.truncate(30) %>
  <%= content_tag :td do %>
    <ul class="list-unstyled">
      <li> Moods: <%= article.mood_list.map {|m| t(m)}.join(', ') %></li>
      <li>Categories: <%= article.category_list.map {|c| t(c)}.join(', ') %></li>
    </ul>
  <% end %>
  <%= content_tag :td do %>
    <%#= link_to t(:show), article_path(article)%>
    <%= link_to t(:edit), edit_article_path(article)%>
  <% end %>
</tr>

app/views/v2/articles/_articles.html.erb
<div class="table-responsive">
   <table class="table table-striped">
     <thead>
       <tr>
         <%= content_tag :th, t(:location) %>
         <%= content_tag :th, t(:title) %>
         <%= content_tag :th, t(:content) %>
         <%= content_tag :th, t(:tags) %>
         <%= content_tag :th, t(:actions) %>
       </tr>
     </thead>
     <tbody>
       <%= render @articles %>
     </tbody>
   </table>
 </div>

app/views/v2/articles/_form.html.erb
<div class='row'>
  <div class='col-md-7'>
    <%= simple_form_for @article do |f| %>
      <%= f.simple_fields_for :article_locations do |a| %>
        <%= a.input :foursquare_id, label: t('name'), input_html: {class: 'foursquare_location_select'}, hint: t('article.form.name_hint') %>
      <% end %>
      <%= f.input :title, label: t('title'), hint: t('article.form.title_hint') %>
      <%= f.input :content, label: t('content'), input_html: {rows: 4}, hint: t('article.form.content_hint') %>
      <%= f.input :mood_list, label: t('mood_list'), collection: Settler.moods.value.map {|k,v| [v,k]}, input_html: {multiple: true, class: 'select2_tags'}, hint: t('article.form.mood_list_hint') %>
      <%= f.input :category_list, label: t('category_list'), collection: Settler.categories.value.map {|k,v| [v,k]}, input_html: {multiple: true, class: 'select2_tags'}, hint: t('article.form.category_list_hint') %>
      <%= f.submit class: 'btn btn-primary' %>
      <%= link_to 'Cancel', articles_path,  class: 'btn btn-default' %>
    <% end %>
  </div>
</div>

app/views/v2/articles/edit.html.erb
<h3>Edit Article</h3>
<%= render 'form'%>

app/views/v2/articles/index.html.erb
<h2 class="sub-header">Articles</h2>
<ul class="nav nav-tabs">
  
  <li class="<%= params[:all_articles] ? '' : 'active' %>"><%= link_to t('my_articles'), articles_path %></li>
  <li class="<%= params[:all_articles] ? 'active' : '' %>"><%= link_to t('all_articles'), articles_path(all_articles: true) %></li>
</ul>
<%= render 'articles'%>

app/views/v2/articles/new.html.erb
<h3>New Article</h3>
<%= render 'form'%>

app/views/v2/articles/show.html.erb
<%= content_tag :h3, @article.title %>

<dl class="dl-horizontal">
  <dt><%= t(:location)%></dt>
  <dd><%= @article.locations.map(&:name).join(', ')%></dd>
  <dt><%= t(:content)%></dt>
  <dd><%= @article.content%></dd>
  <dt><%= t(:tags)%></dt>
  <dd>
    <ul class="list-unstyled">
      <li>Moods: <%= @article.mood_list.map {|m| t(m)}.join(', ') %></li>
      <li>Categories: <%= @article.category_list.map {|c| t(c)}.join(', ') %></li>
    </ul>
  </dd>
</dl>