config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: 'session'



  api_version(:module => "V1", :path => {:value => "v1"}) do
    root 'articles#index'
    match '/foursquare' => 'foursquare#search', via: :get
    match '/foursquare/:id' => 'foursquare#find', via: :get
    resources :articles
    resources :locations
    resources :users
    match '/configuration' => 'configuration#show', via: :get
  end
  
  
  api_version(:module => "V2", :path => {:value => "v2"}, :default => true) do
    root 'articles#index'
    match '/foursquare' => 'foursquare#search', via: :get
    match '/foursquare/:id' => 'foursquare#find', via: :get
    resources :articles
    resources :locations
    resources :users
    match '/configuration' => 'configuration#show', via: :get
  end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
  acts_as_paranoid
  max_paginates_per 200
  ROLES = ['member', 'admin']
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h
  mount_uploader :avatar, AvatarUploader
  
  has_many :articles
  has_many :locations, through: :articles
  has_many :moods, through: :articles
  has_many :categories, through: :articles
  
  after_update :touch_articles_and_locatinos
  after_update :crop_avatar

  validates :first_name, :last_name, :role, :about, :profession, :nationality, :expert_in, presence: true
  validates :website_url, format: URI::regexp(%w(http https)), allow_blank: true
  validates :twitter_handle, format: /\A([a-zA-Z](_?[a-zA-Z0-9]+)*_?|_([a-zA-Z0-9]+_?)*)\z/, allow_blank: true
  validates :role, inclusion: {in: User::ROLES, message: "Role should be one of #{ROLES.join(", ")}"}
  validates :about, length: {maximum: 270}  
  
  scope :by_mood, -> mood { joins(:moods).where(tags: {name: mood})}
  scope :by_category, -> category { joins(:categories).where(tags: {name: category})}
  scope :by_lat_long, -> lat, long, radius = 1000 { joins(:locations).where(locations: {id: Location.by_lat_long(lat, long, radius).map(&:id)})}
  scope :by_article, -> article_ids {joins(:articles).where(articles: {id: article_ids})} 
  scope :by_location, -> location_ids {joins(:locations).where(locations: {id: location_ids})}
  
  def admin?
    role == 'admin'
  end

  def member?
    role == 'member'
  end

  def full_name
    "#{first_name} #{last_name}"
  end
  
  def crop_avatar
    avatar.recreate_versions! if crop_x.present?
  end
  
  def avatar_versions
   avatar.versions.keys
  end
  
  def avatar_url_prefix
   avatar.url.split("/")[0..-2].join("/") + '/'
  end
  
  def avatar_url_suffix
    avatar.url.split("/").last
  end
  
  
  def self.collection_cache_key
    connection.select_value('select md5(ARRAY_AGG(updated_at)::text) from users')
  end
  
  private
  
  def touch_articles_and_locatinos
    articles.each(&:touch)
    locations.each(&:touch)
  end
  
  
end

app/controllers/v1/users_controller.rb
module V1
  class UsersController < BaseController
    load_and_authorize_resource

    before_action :authorize_json_only
  
    def index
      respond_to do |format|
        format.html { authorize! :manage, User, :message => "Unable to view users" }
        format.json
      end
    end
  
    def show
    end
  
    def new
    end
  
    def create  
      @user.role = 'member'
        
      respond_to do |format|
        if @user.save
          format.html {redirect_to users_path}
          format.json { render json: @user }
        else
          format.html {render :new}
          format.json
        end
      end
    end
  
    def edit
    end
  
    def update
      # required for settings form to submit when password is left blank
      if params[:user][:password].blank?
         params[:user].delete("password")
         params[:user].delete("password_confirmation")
      end
      

      respond_to do |format|

        if @user.update_attributes(user_params)
          format.html  {redirect_to users_path}
          format.json { render json: @user }
        else
          format.html {render :edit}
          format.json
        end
      end
    end
  
    def destroy
      @user.destroy
      respond_to do |format|
        format.html {redirect_to users_path }
        format.json
      end
    end
  
  
    private

    def authorize_json_only
      if request.format != :json
        authorize! :manage, User, :message => "Unable to view users"
      end
    end
  
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :about,
                                    :website_url, :twitter_handle, :expert_in, :nationality, :profession)
    end
  
  end
end

app/controllers/v2/articles_controller.rb
module V2
  class ArticlesController < BaseController
    before_action :authorize_json_only, except: :show

    has_scope :by_mood, type: :array
    has_scope :by_category, type: :array
    has_scope :by_user, type: :array
    has_scope :by_lat_long, using: [:lat, :long, :radius], type: :hash
    has_scope :by_location, type: :array
    
    def index
      @articles = apply_scopes(@articles)
      @articles = @articles.joins(:user, :locations).eager_load(:user, :locations) 
      @articles = @articles.where(user_id: current_user.id) if current_user && !params[:all_articles]  && request.format != :json      
      
      ## Geocoder and will_paginate/kaminari have an issue. tracked here: https://github.com/alexreisner/geocoder/issues/630
      ## Disabled kaminari for now
      # @articles = @articles.page(params[:page]).per(parms[:per_page])
      ## For now do it as an array
      # params[:offset] ||= 0
      # params[:limit] ||= 200
      # @articles = @articles.drop(params[:offset].to_i).take(params[:limit].to_i)
    end

    def show
    end

    def new
      @article.article_locations.new
    end

    def create
      @article.user = current_user
      respond_to do |format|
        if @article.save
          flash[:notice] = "Article added!! Add another? (or #{ActionController::Base.helpers.link_to('<b>go back</b>'.html_safe, articles_path)})"
          format.html { redirect_to new_article_path}
          format.json { render json: @article }
        else
          format.html { render :new, alert: 'failed :(' }
          format.json
        end
      end
    end

    def edit
      @article.article_locations.first_or_initialize
    end

    def update
      respond_to do |format|
        if @article.update_attributes(article_params)
          format.html { redirect_to articles_path, notice: 'Article updated' }
          format.json { render json: @article }
        else
          format.html { render :new, alert: 'failed :(' }
          format.json
        end
      end
    end

    def destroy
      @article.destroy
      respond_to do |format|
        format.html { redirect_to articles_path, notice: 'Article deleted' }
        format.json
      end
    end

    private

    def authorize_json_only
      if request.format != :json
        authorize! :manage, Article, :message => "Unable to view articles"
      end
    end


    def article_params
      params.require(:article).permit(:title, :content, :foursquare_ids, article_locations_attributes: [:id, :foursquare_id], mood_list:[], category_list:[])
    end

  end
end

app/controllers/v2/base_controller.rb
module V2
  class BaseController < ApplicationController
    load_and_authorize_resource
    before_filter :make_strings_into_arrays
    before_filter :set_cache_key_from_params
    before_filter :update_request_count, only: :show
    
    rescue_from CanCan::AccessDenied do |exception|
      if user_signed_in?
        render 'shared/access_denied'
      else
        redirect_to new_user_session_path
      end
    end
    
    private 
    
    def make_strings_into_arrays
      [:by_mood, :by_article, :by_user, :by_category, :by_location].each do |name|
        params[name] = [params[name]] if params[name].is_a? String
      end
    end
    
    def set_cache_key_from_params
      #these are the only params used to determine the content of the json partial FOR A SINGLE OBJECT
      @cache_key = params.slice(:by_user, :controller, :include_foursquare).hash
    end
    
    def update_request_count
      resource = instance_variable_get("@#{controller_name.singularize}")
      resource.update_column(:request_count, resource.request_count.to_i + 1)
    end
    
  end
end

app/controllers/v2/configuration_controller.rb
module V2
  class ConfigurationController < BaseController
   skip_load_resource 
    def show
      @categories = Settler.categories.value
      @moods = Settler.moods.value
    end
    
    def update
    end
    
  end
end

app/controllers/v2/foursquare_controller.rb
module V2
  class FoursquareController < BaseController
    skip_load_resource 
    def search
      venues = Foursquare.search_venues(params[:query])
      SearchMiss.create(query: params[:query]) if venues.empty?
      render json: venues
    end
    
    def find
      render json: Foursquare.fetch_venue(params[:id])
    end
  end
end

app/controllers/v2/locations_controller.rb
module V2
  class LocationsController < BaseController
    has_scope :by_mood, type: :array
    has_scope :by_category, type: :array
    has_scope :by_user, type: :array
    has_scope :by_lat_long, using: [:lat, :long, :radius], type: :hash
    
    
    def index      
      @locations = apply_scopes(@locations)  
      # Use eager load to avoid including all users when locations are filtered by a specific user.
      @locations = @locations.joins(articles: :user).eager_load(:articles, articles: :user)      
            
      ## Geocoder and will_paginate/kaminari have an issue. tracked here: https://github.com/alexreisner/geocoder/issues/630
      ## Disabled kaminari for now
      # @locations = @locations.page(params[:page]).per(parms[:per_page])
      ## For now do it as an array
      # params[:offset] ||= 0
      # params[:limit] ||= 200
      # @locations = @locations.drop(params[:offset].to_i).take(params[:limit].to_i)
    end
    
  end
end

app/controllers/v2/users_controller.rb
module V2
  class UsersController < BaseController
    before_action :authorize_json_only
    
    has_scope :by_mood, type: :array
    has_scope :by_category, type: :array
    has_scope :by_lat_long, using: [:lat, :long, :radius], type: :hash
    has_scope :by_article, type: :array
    has_scope :by_location, type: :array
  
    def index
      @users = apply_scopes(@users)
      @users = @users.joins(articles: :locations).eager_load(:articles, articles: :locations) 


      ## Geocoder and will_paginate/kaminari have an issue. tracked here: https://github.com/alexreisner/geocoder/issues/630
      ## Disabled kaminari for now
      # @users = @users.page(params[:page]).per(parms[:per_page])
      ## For now do it as an array
      # params[:offset] ||= 0
      # params[:limit] ||= 200
      # @users = @users.drop(params[:offset].to_i).take(params[:limit].to_i)    
    end
  
    def show
    end
  
    def new
    end
  
    def create
      @user.role = 'member'
      if @user.save
        if user_params[:avatar].present? 
          flash[:notice] = 'Go crop yo-self!'
          render :crop
        else
          flash[:notice] = 'Saved. Thank you!'
          redirect_to users_path
        end
      else
        render :new
      end
    end
  
    def edit
    end
  
    def update
      # required for settings form to submit when password is left blank
      if params[:user][:password].blank?
         params[:user].delete("password")
         params[:user].delete("password_confirmation")
      end
    
      if @user.update_attributes(user_params)
        if user_params[:avatar].present?
          flash[:notice] = 'Go crop yo-self!'
          render :crop
        else
          flash[:notice] = "Relax, you've been saved..."
          redirect_to articles_path
        end
      else
        render :edit
      end
    end
  
    def destroy
      @user.destroy
      respond_to do |format|
        format.html {redirect_to users_path }
        format.json
      end
    end
  
  
    private

    def authorize_json_only
      if request.format != :json
        authorize! :manage, User, :message => "Unable to view users"
      end
    end
  
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :about,
                                    :website_url, :twitter_handle, :expert_in, :nationality, :profession,
                                    :avatar, :avatar_cache, :crop_x, :crop_y, :crop_w, :crop_h)
    end
  
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/v2/users/_form.html.erb
<div class='row'>
  <div class='col-md-8'>
    <%= simple_form_for @user, :html => {:multipart => true} do |f| %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <%= content_tag :h3, t('tell_the_world')%>
        </div>
        <div class="panel-body">
          <div class='row'>
            <div class='col-md-6'>
              <%= f.input :first_name, label: t('first_name') %>    
              <%= f.input :last_name, label: t('last_name') %>
            </div>
            <div class='col-md-6'>
              <div class="fileinput fileinput-new" data-provides="fileinput">
                <div class="fileinput-new thumbnail" style="width: 180px; height: 180px;">
                  <%= image_tag @user.avatar.iphone.url, class: 'img-circle'%>
                </div>
                <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 180px; max-height: 180px;"></div>
                <div>
                  <span class="btn btn-default btn-file">
                    <span class="fileinput-new">Select image</span>
                    <span class="fileinput-exists">Change</span>
                    <%= f.input_field :avatar, as: :file %>
                  </span>
                  <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Cancel</a>
                </div>
              </div>
      				<%= f.hidden_field :avatar_cache %>
            </div>
          </div>
          <%= f.input :expert_in, label: t('expert_in'), hint: t('user.form.expert_in_hint')  %>
          <%= f.input :about, label: t('about'), hint: t('user.form.about_hint'), input_html: {rows: 3} %>
          <%= f.input :nationality, label: t('nationality') %>
          <%= f.input :profession, label: t('profession'), hint: t('user.form.profession_hint') %>
          <%= f.input :website_url, label: t('website_url') %>
          <%= f.input :twitter_handle, label: t('twitter_handle') %>
  				
        </div>
      </div>
    
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3><small>Shhhhh...</small></h3>
        </div>
        <div class="panel-body">
          <%= f.input :email, label: t('email') %>
          <%= f.input :password, label: t('password') %>
          <%= f.input :password_confirmation, label: t('password_confirmation') %>
        </div>
      </div>


      <%= f.submit class: 'btn btn-primary' %>
      <%= link_to 'Cancel', articles_path,  class: 'btn btn-default' %>
      
    <% end %>
  </div>
</div>

app/views/v2/users/_user.html.erb
<tr>
  <%= content_tag :td, user.first_name %>
  <%= content_tag :td, user.last_name %>
  <%= content_tag :td do %>
    <ul class="list-unstyled">
      <% user.articles.each do |a| %>
        <%= content_tag :li, a.title %>
      <% end %>
    </ul>
  <% end %>
  <%= content_tag :td do %>
    <%= link_to t(:edit), edit_user_path(user) %>
  <% end %>
</tr>

app/views/v2/users/_users.html.erb
<div class="table-responsive">
   <table class="table table-striped">
     <thead>
       <tr>        
         <%= content_tag :th, t(:first_name) %>
         <%= content_tag :th, t(:last_name) %>
         <%= content_tag :th, t(:articles) %>
         <%= content_tag :th, t(:actions) %>
       </tr>
     </thead>
     <tbody>
       <%= render @users %>
     </tbody>
   </table>
 </div>

app/views/v2/users/crop.html.erb
<h1>Crop Avatar</h1>
<hr/>
<div class='row'>

  <div class='col-md-2'>
    <h4>Preview</h4>
    <div style="width:100px; height:100px; overflow:hidden" class="img-circle">
      <%= image_tag @user.avatar.url(:large), :id => "preview" %>
    </div>
    
    <br/>
    <%= form_for @user do |f| %>
      <% %w[x y w h].each do |attribute| %>
        <%= f.hidden_field "crop_#{attribute}" %>
      <% end %>
      <div class="actions">
        <%= f.submit "Crop", class: 'btn btn-primary' %>
      </div>
    <% end %>
  </div>
  <div class='col-md-7'>
    <%= image_tag @user.avatar_url(:large), id: "cropbox" %>
  </div>
</div>

app/views/v2/users/edit.html.erb
<%= render 'form'%>

app/views/v2/users/index.html.erb
<h2 class="sub-header">Users</h2>
<%= link_to 'Add New User', new_user_path %>
<%= render 'users'%>

app/views/v2/users/new.html.erb
<%= render 'form'%>