config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: 'session'



  api_version(:module => "V1", :path => {:value => "v1"}) do
    root 'articles#index'
    match '/foursquare' => 'foursquare#search', via: :get
    match '/foursquare/:id' => 'foursquare#find', via: :get
    resources :articles
    resources :locations
    resources :users
    match '/configuration' => 'configuration#show', via: :get
  end
  
  
  api_version(:module => "V2", :path => {:value => "v2"}, :default => true) do
    root 'articles#index'
    match '/foursquare' => 'foursquare#search', via: :get
    match '/foursquare/:id' => 'foursquare#find', via: :get
    resources :articles
    resources :locations
    resources :users
    match '/configuration' => 'configuration#show', via: :get
  end
  
end

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-default navbar-static-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag('/fromto.png'), "/app", class: "navbar-brand"%>
    </div>
    <div class="navbar-collapse collapse">
      

      <p class="navbar-text navbar-right">
        <% if user_signed_in? %>
            Signed in as <%= link_to current_user.full_name, edit_user_path(current_user) %>
            |
            <%= link_to "Sign Out", destroy_user_session_path, {method: :delete} %>
        <% else %>
            <%= link_to "Sign In", new_user_session_path %>
        <% end %>
      </p>
      <% if user_signed_in? %>
        <ul class="nav navbar-nav navbar-right">
            <li class="<%= I18n.locale == :en ? 'active' : '' %>"><%= link_to "en", locale: "en"%></li>
            <li class="<%= I18n.locale == :es ? 'active' : '' %>"><%= link_to "es", locale: "es" %></li>
            <li class=" divider-vertical"></li>
        </ul>
      <% end %>
      
    </div>
  </div>
</div>

app/views/layouts/_sidebar.html.erb
<ul class="nav nav-pills nav-stacked sidebar">
  <li id='sidebar-thumbnail'>
      <%= image_tag current_user.avatar.thumb.url, class: 'img-circle'%>
  </li>
  <%= content_tag :li, link_to(t(:users), users_path) if current_user.admin? %>
  <%= content_tag :li, link_to(t(:articles), articles_path) %>
  <%= content_tag :li, link_to(t(:add_an_article), new_article_path) if can? :create, Article %>
  <%= content_tag :li, link_to(t(:edit_my_profile), edit_user_path(current_user)) %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fromto</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/navbar' %>

  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-2 col-sm-offset-1">
        <%= render 'layouts/sidebar' %>
      </div>
      <div class="col-sm-8 ">
        <% flash.each do |name, msg| %>
          <% if msg.is_a?(String) %>
            <div class="alert alert-dismissable alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              <%= content_tag :div, msg.html_safe, :id => "flash_#{name}" %>
            </div>
          <% end %>
        <% end %>
        <%= yield %>
      </div>
    </div>
  </div>

</body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fromto</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <style>
  body {
    padding-bottom: 40px;
    background-color: #eee;
  }

  form {
    max-width: 370px;
    padding: 15px;
    margin: 0 auto;
  }
  form .form-signin-heading,
  form .checkbox {
    margin-bottom: 10px;
  }
  form .checkbox {
    font-weight: normal;
  }
  form .form-control {
    position: relative;
    height: auto;
    -webkit-box-sizing: border-box;
       -moz-box-sizing: border-box;
            box-sizing: border-box;
    padding: 10px;
    font-size: 16px;
  }
  form .form-control:focus {
    z-index: 2;
  }
  form input[type="email"] {
    margin-bottom: -1px;
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
  }
  form input[type="password"] {
    margin-bottom: 10px;
    border-top-left-radius: 0;
    border-top-right-radius: 0;
  }
  
  </style>
</head>
<body>
  
  <%= render 'layouts/navbar' %>
  

  <div class="container">
    <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <div class="alert alert-dismissable alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
      <% end %>
    <% end %>
    
    
    <%= yield %>
        

  </div>

</body>
</html>